version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: spur_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mavihs
      POSTGRES_DB: spur_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: spur_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: spur_backend
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    ports:
      - "4000:3000"
    env_file:
      - .env
    command: sh -c "npx prisma migrate deploy && node dist/server.js"

volumes:
  postgres_data:
